---
- hosts: kube
  become: true

  vars_files:
    - vars/main.yml

  roles:
  - name: geerlingguy.security
  - name: geerlingguy.swap
  - name: geerlingguy.docker
  - name: geerlingguy.kubernetes